### ISSUE TITLE
【登录和注册页】设计 

### ISSUE THREAD

**Issue by mkz100** [mkz100/hiwi#10]
提供取消返回前一页的选择
![image](https://cloud.githubusercontent.com/assets/247434/19633261/6133eda6-9964-11e6-99e9-78b290dba110.png)

页面输入的顺序 ：

请输入手机号 、 邮箱
输入图形码
获取验证码         输入验证码

![4a2d739e-9963-11e6-8bca-87e7a7133fa8](https://cloud.githubusercontent.com/assets/247434/19842188/9ccd6ddc-9ed3-11e6-9f26-cf46f0bc4cb0.png)

**Comment by 365102010** [comment]
已修改

**Comment by mkz100** [comment]
立即注册 要挪一下

键盘遮挡问题

键盘“前往” 、 Enter 键不工作
