### ISSUE TITLE
【个人信息】

### ISSUE THREAD

**Issue by mkz100** [mkz100/hiwi#112]
1.  完善资料页 / 登录第二页 缺个“网址” 信息
2. 后台会员管理 缺个“网址”
3. 
![image](https://cloud.githubusercontent.com/assets/247434/21212195/103529f2-c23f-11e6-969e-b30ff835489b.png)

![image](https://cloud.githubusercontent.com/assets/247434/21209403/e099eb80-c228-11e6-9392-2473cc6b940a.png)

**Comment by 365102010** [comment]
OK
