### ISSUE TITLE
【邮箱注册】

### ISSUE THREAD

**Issue by mkz100** [mkz100/hiwi#127]
1. 【同一邮箱可以重复注册】同一号码可能也是如此
2. 点击【获取验证码】，如果没有输入邮箱，请提示。
3. **输入错误验证码，系统“验证成功”，提示“验证码已经发送”！**
4.  输入验证码后，如果按“Enter" 或者 ”前往“键，系统提示 ”没有输入验证码“。
5. 这之后，再输入正确验证码，系统提示“成功发送验证码”。但实际上，没有送出验证码。

**Comment by 365102010** [comment]
脚本错误，已改。重复手机号和邮件注册的时候都不会成功
