### ISSUE TITLE
【注册第二页-完善资料】

### ISSUE THREAD

**Issue by mkz100** [mkz100/hiwi#128]
1. 加一个半透明按钮 “跳过，以后完善”
2. 用户按 “取消”，“保存” 或者 “跳过，以后完善” 后，直接进入主页。

![image](https://cloud.githubusercontent.com/assets/247434/21290396/dd3a3854-c46d-11e6-94c4-c02cf7dd9cdf.png)

**Comment by 365102010** [comment]
取消改成以后完善，浮动的会遮挡内容
