### ISSUE TITLE
【搜索页】可以用 昵称，手机号码，邮箱进行搜索和过滤

### ISSUE THREAD

**Issue by hiwibang** [mkz100/hiwi#2]
![image](https://cloud.githubusercontent.com/assets/247434/19631591/5391a2ee-9953-11e6-836c-e1a9edf6687c.png)

**Comment by mkz100** [comment]
搜索和过滤不工作

**Comment by mkz100** [comment]
可以用 昵称，手机号码，邮箱， 标题，内容，关键字 进行搜索

过滤不工作

返回搜索页，显示搜索内容
