### ISSUE TITLE
【完善资料】

### ISSUE THREAD

**Issue by mkz100** [mkz100/hiwi#79]
【修改头像】
1. 可能没有缩略。不能上传3MB的照片。
2. 上传的时候没有显示”等待“光标。
3. 点击后直接打开相册
4. 头像大小《20KB

![image](https://cloud.githubusercontent.com/assets/247434/20995121/b067b5fc-bca9-11e6-8ae5-344a2485f9cf.png)

**Comment by 365102010** [comment]
选择文件是浏览器的功能，直接打开相册不能保证，每个浏览器实现的不一样，一般会选择文件夹

**Comment by mkz100** [comment]
去掉照片
